### ISSUE TITLE
Clues

### ISSUE THREAD

**Issue by ghost** [atjeff/Osrs-Wrapper#2]
Missing Clues hiscores, and I think the BH/LMS ones are bugged as a result of that.

**Comment by atjeff** [comment]
@Magnaboy Thanks for pointing that out! It's highly likely the API has changed... I'll have to take a look this weekend.

**Comment by ghost** [comment]
Also it seems that newly added items aren't able to be looked up in the G.E

**Comment by atjeff** [comment]
This should be addressed by #3. Going to merge and publish tomorrow.
