### ISSUE TITLE
Fix - CORS error in Google Chrome for localhost debugging

### ISSUE THREAD

**Issue by KuroyukiDev** [atjeff/Osrs-Wrapper#6]
Please add Cross Domain Access support for http://localhost:*

adding this line should do it:

`Access-Control-Allow-Origin: http://localhost:*` 

Thanks

**Comment by atjeff** [comment]
@KuroyukiDev, thank you for your suggestion. Unfortunately, I don't believe CORS is a concern of this library and therefore won't be making the change. Feel free to fork the repo if you believe this change is needed 👍
